# Generated by Django 4.1.3 on 2022-11-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Pro_02", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="Me",
        ),
    ]
